---
title: "Final"
author: "Lukas Lescano"
date: "06-09-2025"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    toc-floating: true
execute:
  message: false
  warning: false 
---

The link to my GitHub repository is
[here](https://github.com/lperusa7/ENVS-193DS_spring-2025_final)

## Setup

```{r, packages and data}
# Reading in pakages
library(tidyverse)
library(janitor)
library(here)
library(ggeffects)
library(MuMIn)

# Loading in data
sst <- read_csv(
  here("data", "sst.csv") # file path
)
```

# Problem 1. Research writing

## a. Transparent statistical methods

In part 1, my co-worker used a **correlation test**, specifically a **Pearson's correlation**, to test the linear relationship between **distance from headwater** and **annual total nitrogen load**. We know this because of the phrasing "there is no correlation" which indicates that they tested the correlation between these two continuous variables, which knowing the variables are continuous tells us to use a Pearson's r correlation.
In part 2, my co-worker used a Analysis of Variance (ANOVA) test to be able to asses whether there are any statistically significant differences in the **average nitrogen load** across **multiple sources** (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands). This is evident because the nature of an ANOVA is that the test compares means across more than two groups, which is suggested by the wording "difference in average nitrogen load between sources". 

## b. More information needed

To better interpret the results of the ANOVA in part 2 we should add two additional pieces of information for context. The first is including the **effect size**, by calculating the Eta squared. The addition of an effect size to the context essentially **quantifies the proportion of variance in nitrogen load** between the different sources. Ultimately, this helps us determine whether the effect is **small, medium, or large**, which adds significance to the results. For example, if we got an Eta squared value of 0.20, this would indicate that **20% of the variability in the response can be explained by the source**. Additionally, we should also include a **post-hoc test**, specifically a **Tukey's HSD**, because the ANOVA only tells us that **at least one group differs**, but not specifically which group(s) are significantly different. A Tukey's HSD compares all possible pairs of group means (e.g. **urban land vs. fertilizer, fertilizer vs. grasslands**). This helps clarify which specific sources differ in nitrogen load, which is essential for the interpretation of the results. For example, the test may reveal that the fertilizer group and wastewater treatment group nitrogen loads are significantly higher than those from the atmospheric deposition and grasslands.

## c. Suggestions for rewriting

Part 1:
We found that there is a **small/moderate/strong** association between **distance from headwater (km)** and **annual total nitrogen load (kg year^-1)** (Pearson's r = correlation coefficient, p = 0.03, $\alpha = significance level)

Part 2:
We found a **small/medium/large** difference (Eta squared = effect size value) between sources (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) in average nitrogen load (one-way ANOVA, F(df, df) = test statistic, p = 0.02, $\alpha = significance level)
On average, average nitrogen loads in **Group A** tended to be **higher/lower** than in **Group B** (how much higher or lower from Tukey's HSD, 95% CI [range] kg year^-1), **Group C** (how much higher or lower from Tukey's HSD, 95% CI [range] kg year^-1), **Group D** (how much higher or lower from Tukey's HSD, 95% CI [range] kg year^-1), and **Group E** (how much higher or lower from Tukey's HSD, 95% CI [range] kg year^-1).

# Problem 2. Data visualization

## a. Cleaning and summarizing

## b. Visualize the data


# Problem 3. Data analysis

## a. Response variable

## b. Purpose of study

## c. Difference in “seasons”

## d. Table of models

## e. Run the models

## f. Check the diagnostics

## g. Select the best model

## h. Visualize the model predictions

## i. Write a caption for your figure.

## j. Calculate model predictions

## k. Interpret your results


# Problem 4. Affective and exploratory visualizations

## a. Comparing visualizations

## b. Sharing your affective visualization